using System.Text;

namespace TrueBase.Editor
{
    /// <summary>
    /// PlayNanooRuntime&lt;TRow&gt; 서브클래스 소스를 생성합니다.
    /// SupabaseSettingsEditor의 "PlayNanoo 이관 런타임" 섹션에서 호출됩니다.
    /// </summary>
    public static class PlayNanooRuntimeClassGenerator
    {
        /// <summary>
        /// 서브클래스 C# 소스를 반환합니다.
        /// </summary>
        /// <param name="runtimeClassName">생성할 클래스 이름. 예: "GameRuntime"</param>
        /// <param name="saveClassName">StaticUserSave 서브클래스 이름. 예: "PlayerSave"</param>
        public static string GenerateSource(string runtimeClassName, string saveClassName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// PlayNanooRuntime 서브클래스 — 직접 편집하지 마세요.");
            sb.AppendLine("// SupabaseSettings Inspector > PlayNanoo 이관 런타임 > 런타임 클래스 생성 버튼으로 재생성합니다.");
            sb.AppendLine();
            sb.AppendLine($"public class {runtimeClassName} : PlayNanooRuntime<{saveClassName}.Row> {{ }}");
            return sb.ToString();
        }
    }
}
